### ISSUE TITLE
About character size for serial port

### ISSUE THREAD

**Issue by flywww** [armadsen/ORSSerialPort#117] opened 2017-03-09 09:57 UTC
Hi Armadsen,
I use rs232 for receive my data from hardware.
And my character size set 7 in my hardware serial port. But the ORSSerialPort can't support change parameter of character size. Will you consider add it next version?
Thank you.

**Comment by armadsen** [comment] 2018-07-02 05:47
Closing as duplicate of #85.

**Closed by armadsen** 2018-07-02 05:47 UTC
Labels: duplicate
