### ISSUE TITLE
Address Sanitizer reports use of deallocated memory in sendData:

### ISSUE THREAD

**Issue by kirk-kerekes** [armadsen/ORSSerialPort#106] opened 2016-08-12 15:30 UTC
Address Sanitizer _intermittently_ reports use of deallocated memory in **sendData**:, as invoked by **sendNextRequest**->**reallySendRequest:**. 
My guess is over-aggressive ARC activity -- the  request is deleted from the requests queue, and _then_ sent. 

Ought to be OK, but there are enough async activities floating around to make me wonder.

**Comment by armadsen** [comment] 2016-08-12 17:09
Hi Kirk,

Thanks very much for the report. I'll take a look at this. Either way, I'd rather not have address sanitizer complaining about anything!

**Comment by armadsen** [comment] 2016-12-12 19:23
So far I'm unable to reproduce this in the (Objective-C) RequestResponseDemo example project included with ORSSerialPort. Running the app for a while with Address Sanitizer enabled does not result in any flagged errors. @kirk-kerekes: Are you able to provide any further information about reproducing this?

**Comment by kirk-kerekes** [comment] 2016-12-12 19:29
Only that my app is likely more complicated and busier than the example app.

**Comment by armadsen** [comment] 2018-07-02 05:45
Closing this due to inability to reproduce it.

**Closed by armadsen** 2018-07-02 05:45 UTC
Labels: bug
